/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtikaRouteImport } from './routes/atika'
import { Route as MeerabRouteImport } from './routes/meerab'
import { Route as TogetherRouteImport } from './routes/together'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtikaRoute = AtikaRouteImport.update({
  id: '/atika',
  path: '/atika',
  getParentRoute: () => rootRouteImport,
} as any)
const MeerabRoute = MeerabRouteImport.update({
  id: '/meerab',
  path: '/meerab',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atika': typeof AtikaRoute
  '/meerab': typeof MeerabRoute
  '/together': typeof TogetherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atika': typeof AtikaRoute
  '/meerab': typeof MeerabRoute
  '/together': typeof TogetherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atika': typeof AtikaRoute
  '/meerab': typeof MeerabRoute
  '/together': typeof TogetherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atika' | '/meerab' | '/together'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atika' | '/meerab' | '/together'
  id: '__root__' | '/' | '/atika' | '/meerab' | '/together'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtikaRoute: typeof AtikaRoute
  MeerabRoute: typeof MeerabRoute
  TogetherRoute: typeof TogetherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atika': {
      id: '/atika'
      path: '/atika'
      fullPath: '/atika'
      preLoaderRoute: typeof AtikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meerab': {
      id: '/meerab'
      path: '/meerab'
      fullPath: '/meerab'
      preLoaderRoute: typeof MeerabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtikaRoute: AtikaRoute,
  MeerabRoute: MeerabRoute,
  TogetherRoute: TogetherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
